gpus: 0
max_epochs: 5
# weights_summary: full  # default
# track_grad_norm: 2 # tracking grad norm when training
# log_gpu_memory: True # conflict with GPU Monitor Callbacks?
check_val_every_n_epoch: 5
# overfit_batches: 1
# DEBUG
fast_dev_run: True # fast debug, no log, no checkpoint.
#limit_train_batches: 0.1
#limit_val_batches: 0.1
#limit_test_batches: 0.1
